target("smallfw-blocksruntime")
    set_group("runtime/blocks")
    set_kind("static")
    set_languages("gnu23")
    set_warnings("none")
    add_rules("utils.install.cmake_importfiles")
    add_rules("utils.install.pkgconfig_importfiles")
    add_includedirs("src", smallfw.project_path("Runtime", "SFRuntime", "src"), {public = true})
    add_headerfiles("src/blocksruntime/Block.h", "src/blocksruntime/Block-private.h", {prefixdir = "blocksruntime"})
    add_headerfiles("src/SFBlocksRuntime.modulemap", {prefixdir = "."})
    add_files("src/blocksruntime/data.c", "src/blocksruntime/runtime.c")
    if is_plat("linux") then
        add_defines("_POSIX_C_SOURCE=200809L", {force = true})
    end
    add_cflags("-Wno-everything", {force = true})
