target("smallfw-stdlib")
    set_group("stdlib")
    smallfw.configure_runtime_library_target()
    add_deps(smallfw.runtime_binary_dependency(), {public = true})
    add_includedirs(smallfw.project_path(), {public = true})
    add_headerfiles("*.h", {prefixdir = "stdlib"})
    add_files("*.m", {mflags = {"-fno-objc-arc"}})
