set_project("smallfw")
set_xmakever("3.0.8")

add_rules("mode.debug", "mode.release", "mode.test")

set_languages("gnu23", "gnuxx26")
set_policy("check.auto_ignore_flags", false)
add_rules("plugin.compile_commands.autoupdate")

add_moduledirs("xmake/modules")
add_repositories("smallfw-local .", {rootdir = os.scriptdir()})

includes("xmake/options.lua")
includes("xmake/rules.lua")
includes("Runtime")
includes("StandardLibrary")
includes("examples")
includes("benchmarking")
includes("tools/generics-plugin")
includes("xmake/tasks/common.lua")
includes("xmake/tasks/runtime_bench.lua")
includes("xmake/tasks/runtime_coverage.lua")
includes("xmake/tasks/runtime_fuzz.lua")
includes("xmake/tasks/runtime_performance_matrix.lua")
includes("xmake/tasks/runtime_profile.lua")
includes("xmake/tasks/scan_build.lua")
