set_project("smallfw")

add_rules("mode.debug", "mode.release")

set_languages("c11", "cxx11")
set_toolchains("clang")
set_policy("check.auto_ignore_flags", false)
add_rules("plugin.compile_commands.autoupdate")

add_moduledirs("xmake/modules")

includes("xmake/project/options.lua")
includes("xmake/project/runtime.lua")
includes("src/runtime")
includes("StandardLibrary")
includes("tests/runtime")
includes("tests/stdlib")
includes("benchmarks/runtime-bench")
includes("examples/particle-sim")
includes("tests/fuzz/dispatch")
includes("tests/fuzz/loader")
includes("tests/fuzz/exceptions")
includes("xmake/tasks/common.lua")
includes("xmake/tasks/clang_format.lua")
includes("xmake/tasks/runtime_bench.lua")
includes("xmake/tasks/runtime_coverage.lua")
includes("xmake/tasks/runtime_fuzz.lua")
includes("xmake/tasks/runtime_performance_matrix.lua")
includes("xmake/tasks/runtime_profile.lua")
includes("xmake/tasks/runtime_sanitize.lua")
includes("xmake/tasks/scan_build.lua")
