import("lib.detect.find_program")

local function _trim(value)
    return tostring(value or ""):gsub("^%s+", ""):gsub("%s+$", "")
end

local function _try_output(program, args)
    local ok, output = try {
        function ()
            return true, os.iorunv(program, args or {})
        end,
        catch {
            function ()
                return false, nil
            end
        }
    }
    if ok then
        return _trim(output)
    end
    return nil
end

local function _llvm_includedir()
    local candidates = {
        find_program("llvm-config"),
        find_program("llvm-config-22"),
        find_program("llvm-config-21"),
        "llvm-config",
    }
    for _, candidate in ipairs(candidates) do
        if candidate ~= nil and candidate ~= "" then
            local includedir = _try_output(candidate, {"--includedir"})
            if includedir ~= nil and includedir ~= "" and os.isdir(includedir) then
                return includedir
            end
        end
    end

    local dirs = os.dirs("/usr/lib/llvm-*/include")
    table.sort(dirs)
    for index = #dirs, 1, -1 do
        if os.isfile(path.join(dirs[index], "clang", "AST", "ASTConsumer.h")) then
            return dirs[index]
        end
    end
    return nil
end

local function _append(lines, ...)
    for _, line in ipairs({...}) do
        table.insert(lines, line)
    end
end

function config_text()
    local lines = {}
    _append(lines,
        "# This file is generated by xmake. Do not edit by hand.",
        "# Regenerate with `xmake generate-clangd` or any normal `xmake build`.",
        "",
        "CompileFlags:",
        "  CompilationDatabase: .",
        "  Remove:",
        "    - -fmodules-cache-path=*",
        "    - -fmodule-cache-path=*",
        "    - -fbuild-session-file=*",
        "    - -fbuild-session-timestamp=*",
        "    - -fmodules-validate-once-per-build-session",
        "    - -fmodules-prune-interval=*",
        "    - -fmodules-prune-after=*",
        "    - -fprebuilt-module-path=*",
        "    - -fprebuilt-implicit-modules",
        "    - -fmodule-file=*",
        "    - -fno-implicit-module-maps",
        "    - -fplugin=*",
        "    - -fpass-plugin=*",
        "    - -load",
        "    - -plugin",
        "    - -plugin-arg-*",
        "    - -fprofile-instr-generate*",
        "    - -fprofile-instr-use=*",
        "    - -fcoverage-mapping",
        "  Add:",
        "    - --target=x86_64-pc-linux-gnu",
        "    - -std=gnu2x",
        "    - -fmodules-cache-path=build/.clangd/clang-module-cache",
        "    - -fno-builtin-module-map",
        "    - -fno-modules-validate-system-headers",
        "    - -Wno-explicit-ownership-type",
        "    - \"-D__SIZE_TYPE__=long unsigned int\"",
        "    - \"-D__PTRDIFF_TYPE__=long int\"",
        "    - \"-D__WCHAR_TYPE__=int\"",
        "    - \"-D__WINT_TYPE__=unsigned int\"",
        "    - \"-D__INT64_TYPE__=long int\"",
        "    - \"-D__UINT64_TYPE__=long unsigned int\"",
        "    - \"-D__INTPTR_TYPE__=long int\"",
        "    - \"-D__UINTPTR_TYPE__=long unsigned int\"",
        "    - \"-D__UINT64_MAX__=18446744073709551615UL\"",
        "    - \"-D__UINTPTR_MAX__=18446744073709551615UL\"",
        "    - -D__ATOMIC_RELAXED=0",
        "    - -D__ATOMIC_CONSUME=1",
        "    - -D__ATOMIC_ACQUIRE=2",
        "    - -D__ATOMIC_RELEASE=3",
        "    - -D__ATOMIC_ACQ_REL=4",
        "    - -D__ATOMIC_SEQ_CST=5",
        "    - -D__x86_64__=1",
        "    - -D__LP64__=1",
        "    - -D__linux__=1",
        "    - -D__gnu_linux__=1",
        "",
        "Index:",
        "  Background: Build",
        "",
        "Diagnostics:",
        "  UnusedIncludes: None",
        "  MissingIncludes: None",
        "  ClangTidy:",
        "    Remove:",
        "      - \"*\"",
        "",
        "---",
        "If:",
        "  PathMatch: .*\\.(m|mm)$",
        "CompileFlags:",
        "  Add:",
        "    - -D__OBJC__=1",
        "    - -D__unsafe_unretained=",
        "",
        "---",
        "If:",
        "  PathMatch: .*\\.mm$",
        "CompileFlags:",
        "  Remove:",
        "    - -std=gnu23",
        "    - -std=gnu2x",
        "  Add:",
        "    - -x",
        "    - objective-c++",
        "    - -std=gnu++26",
        "",
        "---",
        "If:",
        "  PathMatch: .*Runtime/src/.*\\.h",
        "CompileFlags:",
        "  Remove:",
        "    - -fmodules",
        "    - -fimplicit-modules",
        "    - -fmodule-map-file=Runtime/src/SFRuntime.modulemap",
        "",
        "---",
        "If:",
        "  PathMatch: .*Runtime/src/(SmallFW|Blocks)/.*\\.h",
        "CompileFlags:",
        "  Add:",
        "    - -D__OBJC__=1",
        "    - -D__unsafe_unretained=",
        "",
        "---",
        "If:",
        "  PathMatch: .*Runtime/src/.*\\.m",
        "CompileFlags:",
        "  Remove:",
        "    - -fmodules",
        "    - -fimplicit-modules",
        "    - -fmodule-map-file=Runtime/src/SFRuntime.modulemap",
        "    - -fmodule-map-file=StandardLibrary/src/SFStdLib.modulemap",
        "",
        "---",
        "If:",
        "  PathMatch: .*StandardLibrary/src/SFStdLib/.*\\.h",
        "CompileFlags:",
        "  Remove:",
        "    - -fmodules",
        "    - -fimplicit-modules",
        "    - -fmodule-map-file=Runtime/src/SFRuntime.modulemap",
        "    - -fmodule-map-file=StandardLibrary/src/SFStdLib.modulemap",
        "  Add:",
        "    - -D__OBJC__=1",
        "    - -D__unsafe_unretained=",
        "",
        "---",
        "If:",
        "  PathMatch: .*StandardLibrary/src/SFStdLib/.*\\.m",
        "CompileFlags:",
        "  Remove:",
        "    - -fmodule-map-file=StandardLibrary/src/SFStdLib.modulemap",
        "",
        "---",
        "If:",
        "  PathMatch: .*Runtime/tests/(runtime-test.*\\.m|runtime-tests\\.m|runtime-test-support\\.h)",
        "CompileFlags:",
        "  Remove:",
        "    - -fmodules",
        "    - -fimplicit-modules",
        "    - -fmodule-map-file=Runtime/src/SFRuntime.modulemap",
        "    - -fmodule-map-file=StandardLibrary/src/SFStdLib.modulemap",
        "  Add:",
        "    - -DSF_CLANGD_NO_MODULES=1",
        "",
        "---",
        "If:",
        "  PathMatch: .*(generic-metadata|generic-ir).*\\.m",
        "CompileFlags:",
        "  Remove:",
        "    - -DSF_RUNTIME_GENERIC_METADATA=0",
        "  Add:",
        "    - -DSF_RUNTIME_GENERIC_METADATA=1",
        "",
        "---",
        "If:",
        "  PathMatch: .*StandardLibrary/tests/generic-metadata.*\\.m",
        "CompileFlags:",
        "  Remove:",
        "    - -fmodules",
        "    - -fimplicit-modules",
        "    - -fmodule-map-file=Runtime/src/SFRuntime.modulemap",
        "    - -fmodule-map-file=StandardLibrary/src/SFStdLib.modulemap",
        "",
        "---",
        "If:",
        "  PathMatch: .*StandardLibrary/tests/.*\\.m",
        "CompileFlags:",
        "  Remove:",
        "    - -fobjc-arc",
        "  Add:",
        "    - -fno-objc-arc",
        "",
        "---",
        "If:",
        "  PathMatch: .*tools/generics-plugin/clangd-shims/.*\\.h",
        "CompileFlags:",
        "  Remove:",
        "    - -std=gnu23",
        "    - -std=gnu2x",
        "  Add:",
        "    - -x",
        "    - c++-header",
        "    - -std=gnu++17",
        "",
        "---",
        "If:",
        "  PathMatch: .*benchmarking/src/.*\\.m",
        "CompileFlags:",
        "  Add:",
        "    - -fno-implicit-module-maps",
        "",
        "---",
        "If:",
        "  PathMatch: .*tools/generics-plugin/src/.*\\.cpp",
        "CompileFlags:",
        "  Remove:",
        "    - -std=gnu23",
        "    - -std=gnu2x",
        "    - -DIBOutlet=*",
        "    - -DIBOutletCollection*",
        "    - -DIBAction=*",
        "    - -fobjc-runtime=*",
        "    - -fobjc-arc",
        "    - -fobjc-exceptions",
        "    - -fblocks",
        "    - -fconstant-string-class=*",
        "    - -fmodule-map-file=Runtime/src/SFRuntime.modulemap",
        "    - -fmodule-map-file=StandardLibrary/src/SFStdLib.modulemap",
        "  Add:",
        "    - -x",
        "    - c++",
        "    - -std=gnu++17",
        "    - -fno-exceptions",
        "    - -funwind-tables",
        "    - -D_GNU_SOURCE",
        "    - -D__STDC_CONSTANT_MACROS",
        "    - -D__STDC_FORMAT_MACROS",
        "    - -D__STDC_LIMIT_MACROS")

    local includedir = _llvm_includedir()
    if includedir ~= nil and includedir ~= "" then
        _append(lines, "    - -isystem" .. includedir)
    end
    _append(lines, "    - -isystemtools/generics-plugin/clangd-shims")
    _append(lines, "")
    return table.concat(lines, "\n")
end

function write_config(output)
    output = output or path.join(os.projectdir(), ".clangd")
    local text = config_text()
    local old = os.isfile(output) and io.readfile(output) or nil
    os.mkdir(path.join(os.projectdir(), "build", ".clangd"))
    if old ~= text then
        io.writefile(output, text)
        print(".clangd updated")
    end
    return output
end

function clear_cache()
    os.rm(path.join(os.projectdir(), "build", ".clangd", "clang-module-cache"))
end

function source_files()
    local files = {}
    local seen = {}
    local roots = {
        "Runtime",
        "StandardLibrary",
        "benchmarking",
        "examples",
        path.join("tools", "generics-plugin"),
    }
    local suffixes = {"*.c", "*.h", "*.m", "*.mm", "*.cpp", "*.hpp"}
    for _, root in ipairs(roots) do
        for _, suffix in ipairs(suffixes) do
            for _, file in ipairs(os.files(path.join(root, "**", suffix))) do
                local normalized = file:gsub("\\", "/")
                if not seen[normalized] then
                    seen[normalized] = true
                    table.insert(files, normalized)
                end
            end
        end
    end
    table.sort(files)
    return files
end

function check_all(opt)
    opt = opt or {}
    write_config()
    if opt.clear_cache ~= false then
        clear_cache()
    end

    local clangd = find_program("clangd") or "clangd"
    local projectdir = os.projectdir()
    local failures = {}
    local files = source_files()
    for index, file in ipairs(files) do
        print("[%02d] clangd --check %s", index, file)
        local ok, errors = try {
            function ()
                os.runv(clangd, {
                    "--check=" .. file,
                    "--compile-commands-dir=" .. projectdir,
                    "--enable-config",
                    "--log=error",
                    "--tweaks=",
                })
                return true, nil
            end,
            catch {
                function (errors)
                    return false, errors
                end
            }
        }
        if not ok then
            table.insert(failures, string.format("%s: %s", file, tostring(errors)))
        end
    end

    if #failures > 0 then
        raise("clangd failed on %d file(s):\n%s", #failures, table.concat(failures, "\n"))
    end
    print("clangd checked %d file(s)", #files)
end
