target("runtime-tests")
    set_group("tests/runtime")
    set_kind("binary")
    set_default(false)
    if is_mode("release") then
        set_optimize("fastest")
    end
    add_options(smallfw.runtime_build_options)
    add_deps(smallfw.runtime_binary_dependency())
    add_includedirs(smallfw.project_path("Runtime", "SFRuntime", "src"))
    add_includedirs(smallfw.project_path("Runtime", "SFRuntime", "tests"))
    add_rules("smallfw.runtime.common")
    add_rules("smallfw.generic_metadata")
    add_rules("smallfw.runtime.binary")
    if smallfw.is_wasm() then
        add_rules("smallfw.wasm.run")
        add_rules("smallfw.wasm.test")
    end
    add_defines("SF_TEST_ENABLE_SUITE_ARC")
    add_defines("SF_TEST_ENABLE_SUITE_PARENT")
    add_defines("SF_TEST_ENABLE_SUITE_DISPATCH")
    add_defines("SF_TEST_ENABLE_SUITE_LOADER")
    add_files("runtime-tests.m", "runtime-test-support.m", {mflags = {"-fno-objc-arc"}})
    add_files("runtime-test-arc.m", {mflags = {"-fno-objc-arc"}})
    add_files("runtime-test-parent.m", {mflags = {"-fno-objc-arc"}})
    add_files("runtime-test-dispatch.m", {mflags = {"-fno-objc-arc"}})
    add_files("runtime-test-loader.m", {mflags = {"-fno-objc-arc"}})
    if has_config("runtime-tagged-pointers") then
        add_defines("SF_TEST_ENABLE_SUITE_TAGGED")
        add_files("runtime-test-tagged.m", {mflags = {"-fno-objc-arc"}})
    end
    if not smallfw.is_wasm() then
        add_defines("SF_TEST_ENABLE_SUITE_EXCEPTIONS")
        add_files("runtime-test-exceptions.m", {mflags = {"-fno-objc-arc"}})
    end

target("runtime-module-smoke")
    set_group("tests/runtime/modules")
    set_kind("binary")
    set_default(false)
    add_options(smallfw.runtime_build_options)
    add_deps(smallfw.runtime_binary_dependency())
    add_deps("smallfw-blocksruntime")
    add_rules("smallfw.runtime.common")
    add_rules("smallfw.runtime.binary")
    add_files("module-smoke.m", {mflags = {"-fno-objc-arc"}})
    add_tests("runtime_module_smoke", {group = "runtime", realtime_output = true})

target("runtime-tests-arc")
    set_group("tests/runtime/arc")
    set_kind("binary")
    set_default(false)
    if is_mode("release") then
        set_optimize("fastest")
    end
    add_options(smallfw.runtime_build_options)
    add_deps(smallfw.runtime_binary_dependency())
    add_includedirs(smallfw.project_path("Runtime", "SFRuntime", "src"))
    add_includedirs(smallfw.project_path("Runtime", "SFRuntime", "tests"))
    add_rules("smallfw.runtime.common")
    add_rules("smallfw.generic_metadata")
    add_rules("smallfw.runtime.binary")
    if smallfw.is_wasm() then
        add_rules("smallfw.wasm.run")
        add_rules("smallfw.wasm.test")
    end
    add_defines("SF_TEST_SUITE_LABEL=arc", "SF_TEST_SUITE_PROVIDER=sf_runtime_arc_cases")
    add_files("runtime-tests.m", "runtime-test-support.m", "runtime-test-arc.m", {mflags = {"-fno-objc-arc"}})
    add_tests("arc_nil_operations", {group = "runtime", realtime_output = true, runargs = {"--case", "arc_nil_operations"}})
    add_tests("arc_strong_store", {group = "runtime", realtime_output = true, runargs = {"--case", "arc_strong_store"}})
    add_tests("arc_strong_store_self", {group = "runtime", realtime_output = true, runargs = {"--case", "arc_strong_store_self"}})
    add_tests("arc_autorelease_pool", {group = "runtime", realtime_output = true, runargs = {"--case", "arc_autorelease_pool"}})
    add_tests("arc_autorelease_no_pool", {group = "runtime", realtime_output = true, runargs = {"--case", "arc_autorelease_no_pool"}})
    add_tests("arc_nested_autorelease_pools", {group = "runtime", realtime_output = true, runargs = {"--case", "arc_nested_autorelease_pools"}})
    add_tests("arc_marker_capacity_failure", {group = "runtime", realtime_output = true, runargs = {"--case", "arc_marker_capacity_failure"}})
    add_tests("arc_autorelease_pool_fallback_token", {group = "runtime", realtime_output = true, runargs = {"--case", "arc_autorelease_pool_fallback_token"}})
    add_tests("arc_autorelease_capacity_failure", {group = "runtime", realtime_output = true, runargs = {"--case", "arc_autorelease_capacity_failure"}})
    add_tests("arc_factory_return", {group = "runtime", realtime_output = true, runargs = {"--case", "arc_factory_return"}})
    add_tests("arc_retain_release_balance", {group = "runtime", realtime_output = true, runargs = {"--case", "arc_retain_release_balance"}})
    add_tests("arc_dead_object_noop_release", {group = "runtime", realtime_output = true, runargs = {"--case", "arc_dead_object_noop_release"}})
    add_tests("arc_return_value_helpers", {group = "runtime", realtime_output = true, runargs = {"--case", "arc_return_value_helpers"}})
    add_tests("arc_object_method_wrappers", {group = "runtime", realtime_output = true, runargs = {"--case", "arc_object_method_wrappers"}})
    add_tests("arc_object_nonheap_fallbacks", {group = "runtime", realtime_output = true, runargs = {"--case", "arc_object_nonheap_fallbacks"}})
    add_tests("arc_object_alloc_in_place", {group = "runtime", realtime_output = true, runargs = {"--case", "arc_object_alloc_in_place"}})
    add_tests("arc_objc_alloc_init_success", {group = "runtime", realtime_output = true, runargs = {"--case", "arc_objc_alloc_init_success"}})
    add_tests("arc_large_autorelease_growth", {group = "runtime", realtime_output = true, runargs = {"--case", "arc_large_autorelease_growth"}})
    add_tests("arc_large_marker_growth", {group = "runtime", realtime_output = true, runargs = {"--case", "arc_large_marker_growth"}})
    add_tests("arc_pool_pop_marker_clamp", {group = "runtime", realtime_output = true, runargs = {"--case", "arc_pool_pop_marker_clamp"}})
    add_tests("arc_dispose_edge_paths", {group = "runtime", realtime_output = true, runargs = {"--case", "arc_dispose_edge_paths"}})
    add_tests("arc_runtime_test_alloc_wrappers", {group = "runtime", realtime_output = true, runargs = {"--case", "arc_runtime_test_alloc_wrappers"}})
    add_tests("arc_objc_alloc_null", {group = "runtime", realtime_output = true, runargs = {"--case", "arc_objc_alloc_null"}})
    add_tests("arc_objc_alloc_missing_alloc", {group = "runtime", realtime_output = true, runargs = {"--case", "arc_objc_alloc_missing_alloc"}})
    add_tests("arc_objc_alloc_init_missing_init", {group = "runtime", realtime_output = true, runargs = {"--case", "arc_objc_alloc_init_missing_init"}})
    add_tests("allocator_custom_alloc_free", {group = "runtime", realtime_output = true, runargs = {"--case", "allocator_custom_alloc_free"}})
    add_tests("allocator_default_alignment", {group = "runtime", realtime_output = true, runargs = {"--case", "allocator_default_alignment"}})
    add_tests("allocator_default_invalid_alignment", {group = "runtime", realtime_output = true, runargs = {"--case", "allocator_default_invalid_alignment"}})

target("runtime-tests-parent")
    set_group("tests/runtime/parent")
    set_kind("binary")
    set_default(false)
    if is_mode("release") then
        set_optimize("fastest")
    end
    add_options(smallfw.runtime_build_options)
    add_deps(smallfw.runtime_binary_dependency())
    add_includedirs(smallfw.project_path("Runtime", "SFRuntime", "src"))
    add_includedirs(smallfw.project_path("Runtime", "SFRuntime", "tests"))
    add_rules("smallfw.runtime.common")
    add_rules("smallfw.generic_metadata")
    add_rules("smallfw.runtime.binary")
    if smallfw.is_wasm() then
        add_rules("smallfw.wasm.run")
        add_rules("smallfw.wasm.test")
    end
    add_defines("SF_TEST_SUITE_LABEL=parent", "SF_TEST_SUITE_PROVIDER=sf_runtime_parent_cases")
    add_files("runtime-tests.m", "runtime-test-support.m", "runtime-test-parent.m", {mflags = {"-fno-objc-arc"}})
    add_tests("value_parent_layout_hidden_storage", {group = "runtime", realtime_output = true, runargs = {"--case", "value_parent_layout_hidden_storage"}})
    add_tests("value_parent_alloc_embeds_in_parent", {group = "runtime", realtime_output = true, runargs = {"--case", "value_parent_alloc_embeds_in_parent"}})
    add_tests("value_parent_nontrivial_inline_rejected", {group = "runtime", realtime_output = true, runargs = {"--case", "value_parent_nontrivial_inline_rejected"}})
    add_tests("value_parent_duplicate_slots_reuse", {group = "runtime", realtime_output = true, runargs = {"--case", "value_parent_duplicate_slots_reuse"}})
    add_tests("value_parent_child_expires_with_parent", {group = "runtime", realtime_output = true, runargs = {"--case", "value_parent_child_expires_with_parent"}})
    add_tests("value_parent_standalone_heap_alloc", {group = "runtime", realtime_output = true, runargs = {"--case", "value_parent_standalone_heap_alloc"}})
    add_tests("value_parent_slot_exhaustion", {group = "runtime", realtime_output = true, runargs = {"--case", "value_parent_slot_exhaustion"}})
    add_tests("value_parent_oversized_subclass_rejected", {group = "runtime", realtime_output = true, runargs = {"--case", "value_parent_oversized_subclass_rejected"}})
    add_tests("parent_group_inheritance", {group = "runtime", realtime_output = true, runargs = {"--case", "parent_group_inheritance"}})
    add_tests("parent_allocator_propagation", {group = "runtime", realtime_output = true, runargs = {"--case", "parent_allocator_propagation"}})
    add_tests("parent_getter_lifecycle", {group = "runtime", realtime_output = true, runargs = {"--case", "parent_getter_lifecycle"}})
    add_tests("parent_child_outlives_parent", {group = "runtime", realtime_output = true, runargs = {"--case", "parent_child_outlives_parent"}})
    add_tests("parent_group_frees_on_last_release", {group = "runtime", realtime_output = true, runargs = {"--case", "parent_group_frees_on_last_release"}})
    add_tests("parent_nested_allocation_same_root", {group = "runtime", realtime_output = true, runargs = {"--case", "parent_nested_allocation_same_root"}})
    add_tests("parent_alloc_with_nil_parent", {group = "runtime", realtime_output = true, runargs = {"--case", "parent_alloc_with_nil_parent"}})
    add_tests("parent_dead_parent_rejects_new_child", {group = "runtime", realtime_output = true, runargs = {"--case", "parent_dead_parent_rejects_new_child"}})
    if not smallfw.is_wasm() then
        add_tests("parent_concurrent_alloc_release", {group = "runtime", realtime_output = true, runargs = {"--case", "parent_concurrent_alloc_release"}})
    end

target("runtime-tests-dispatch")
    set_group("tests/runtime/dispatch")
    set_kind("binary")
    set_default(false)
    if is_mode("release") then
        set_optimize("fastest")
    end
    add_options(smallfw.runtime_build_options)
    add_deps(smallfw.runtime_binary_dependency())
    add_includedirs(smallfw.project_path("Runtime", "SFRuntime", "src"))
    add_includedirs(smallfw.project_path("Runtime", "SFRuntime", "tests"))
    add_rules("smallfw.runtime.common")
    add_rules("smallfw.generic_metadata")
    add_rules("smallfw.runtime.binary")
    if smallfw.is_wasm() then
        add_rules("smallfw.wasm.run")
        add_rules("smallfw.wasm.test")
        add_rules("smallfw.wasm.browser_smoke", {title = "runtime-tests-dispatch"})
    end
    add_defines("SF_TEST_SUITE_LABEL=dispatch", "SF_TEST_SUITE_PROVIDER=sf_runtime_dispatch_cases")
    add_files("runtime-tests.m", "runtime-test-support.m", "runtime-test-dispatch.m", {mflags = {"-fno-objc-arc"}})
    add_tests("dispatch_cache_warm_hits", {group = "runtime", realtime_output = true, runargs = {"--case", "dispatch_cache_warm_hits"}})
    add_tests("dispatch_super_lookup", {group = "runtime", realtime_output = true, runargs = {"--case", "dispatch_super_lookup"}})
    add_tests("dispatch_selector_equality", {group = "runtime", realtime_output = true, runargs = {"--case", "dispatch_selector_equality"}})
    add_tests("dispatch_selector_lookup_only_registration", {group = "runtime", realtime_output = true, runargs = {"--case", "dispatch_selector_lookup_only_registration"}})
    add_tests("dispatch_method_lookup_canonical", {group = "runtime", realtime_output = true, runargs = {"--case", "dispatch_method_lookup_canonical"}})
    add_tests("dispatch_c_msgsend_signatures", {group = "runtime", realtime_output = true, runargs = {"--case", "dispatch_c_msgsend_signatures"}})
    add_tests("dispatch_c_msgsend_unsupported_float", {group = "runtime", realtime_output = true, runargs = {"--case", "dispatch_c_msgsend_unsupported_float"}})
    add_tests("dispatch_c_internal_helpers", {group = "runtime", realtime_output = true, runargs = {"--case", "dispatch_c_internal_helpers"}})
    add_tests("dispatch_struct_params", {group = "runtime", realtime_output = true, runargs = {"--case", "dispatch_struct_params"}})
    add_tests("dispatch_struct_returns", {group = "runtime", realtime_output = true, runargs = {"--case", "dispatch_struct_returns"}})
    add_tests("dispatch_dtable_lookup", {group = "runtime", realtime_output = true, runargs = {"--case", "dispatch_dtable_lookup"}})
    add_tests("dispatch_forwarding_targets", {group = "runtime", realtime_output = true, runargs = {"--case", "dispatch_forwarding_targets"}})
    if not smallfw.is_wasm() then
        add_tests("dispatch_concurrent_reads", {group = "runtime", realtime_output = true, runargs = {"--case", "dispatch_concurrent_reads"}})
    end

target("runtime-tests-loader")
    set_group("tests/runtime/loader")
    set_kind("binary")
    set_default(false)
    if is_mode("release") then
        set_optimize("fastest")
    end
    add_options(smallfw.runtime_build_options)
    add_deps(smallfw.runtime_binary_dependency())
    add_includedirs(smallfw.project_path("Runtime", "SFRuntime", "src"))
    add_includedirs(smallfw.project_path("Runtime", "SFRuntime", "tests"))
    add_rules("smallfw.runtime.common")
    add_rules("smallfw.generic_metadata")
    add_rules("smallfw.runtime.binary")
    if smallfw.is_wasm() then
        add_rules("smallfw.wasm.run")
        add_rules("smallfw.wasm.test")
    end
    add_defines("SF_TEST_SUITE_LABEL=loader", "SF_TEST_SUITE_PROVIDER=sf_runtime_loader_cases")
    add_files("runtime-tests.m", "runtime-test-support.m", "runtime-test-loader.m", {mflags = {"-fno-objc-arc"}})
    if not smallfw.is_wasm() then
        add_tests("no_libobjc_dependency", {group = "runtime", realtime_output = true, runargs = {"--case", "no_libobjc_dependency"}})
    end
    add_tests("loader_lookup_nulls", {group = "runtime", realtime_output = true, runargs = {"--case", "loader_lookup_nulls"}})
    add_tests("loader_lookup_missing", {group = "runtime", realtime_output = true, runargs = {"--case", "loader_lookup_missing"}})
    add_tests("loader_header_validation", {group = "runtime", realtime_output = true, runargs = {"--case", "loader_header_validation"}})
    add_tests("loader_header_size_modes", {group = "runtime", realtime_output = true, runargs = {"--case", "loader_header_size_modes"}})
    add_tests("loader_class_size_synthetic", {group = "runtime", realtime_output = true, runargs = {"--case", "loader_class_size_synthetic"}})
    add_tests("loader_abi_entrypoint_surface", {group = "runtime", realtime_output = true, runargs = {"--case", "loader_abi_entrypoint_surface"}})
    add_tests("loader_hash_helpers", {group = "runtime", realtime_output = true, runargs = {"--case", "loader_hash_helpers"}})
    add_tests("loader_alloc_failure_paths", {group = "runtime", realtime_output = true, runargs = {"--case", "loader_alloc_failure_paths"}})
    add_tests("loader_class_name_live_object", {group = "runtime", realtime_output = true, runargs = {"--case", "loader_class_name_live_object"}})
    add_tests("loader_manual_registration", {group = "runtime", realtime_output = true, runargs = {"--case", "loader_manual_registration"}})
    if has_config("runtime-reflection") then
        add_tests("reflection_class_lookup", {group = "runtime", realtime_output = true, runargs = {"--case", "reflection_class_lookup"}})
        add_tests("reflection_inherited_method_lookup", {group = "runtime", realtime_output = true, runargs = {"--case", "reflection_inherited_method_lookup"}})
        add_tests("reflection_method_lookup", {group = "runtime", realtime_output = true, runargs = {"--case", "reflection_method_lookup"}})
        add_tests("reflection_ivar_lookup", {group = "runtime", realtime_output = true, runargs = {"--case", "reflection_ivar_lookup"}})
        add_tests("reflection_inherited_ivar_lookup", {group = "runtime", realtime_output = true, runargs = {"--case", "reflection_inherited_ivar_lookup"}})
        add_tests("reflection_null_paths", {group = "runtime", realtime_output = true, runargs = {"--case", "reflection_null_paths"}})
        add_tests("reflection_selector_lookup_only", {group = "runtime", realtime_output = true, runargs = {"--case", "reflection_selector_lookup_only"}})
        add_tests("reflection_failure_paths", {group = "runtime", realtime_output = true, runargs = {"--case", "reflection_failure_paths"}})
        add_tests("reflection_full_map_exhaustion", {group = "runtime", realtime_output = true, runargs = {"--case", "reflection_full_map_exhaustion"}})
    end
    if not smallfw.is_wasm() then
        add_tests("class_lookup_concurrent", {group = "runtime", realtime_output = true, runargs = {"--case", "class_lookup_concurrent"}})
    end

if has_config("runtime-tagged-pointers") then
    target("runtime-tests-tagged")
        set_group("tests/runtime/tagged")
        set_kind("binary")
        set_default(false)
        if is_mode("release") then
            set_optimize("fastest")
        end
        add_options(smallfw.runtime_build_options)
        add_deps(smallfw.runtime_binary_dependency())
        add_includedirs(smallfw.project_path("Runtime", "SFRuntime", "src"))
        add_includedirs(smallfw.project_path("Runtime", "SFRuntime", "tests"))
        add_rules("smallfw.runtime.common")
        add_rules("smallfw.generic_metadata")
        add_rules("smallfw.runtime.binary")
        if smallfw.is_wasm() then
            add_rules("smallfw.wasm.run")
            add_rules("smallfw.wasm.test")
        end
        add_defines("SF_TEST_SUITE_LABEL=tagged", "SF_TEST_SUITE_PROVIDER=sf_runtime_tagged_cases")
        add_files("runtime-tests.m", "runtime-test-support.m", "runtime-test-tagged.m", {mflags = {"-fno-objc-arc"}})
        add_tests("tagged_arc_noop_semantics", {group = "runtime", realtime_output = true, runargs = {"--case", "tagged_arc_noop_semantics"}})
        add_tests("tagged_object_decode_paths", {group = "runtime", realtime_output = true, runargs = {"--case", "tagged_object_decode_paths"}})
        add_tests("tagged_dispatch_methods", {group = "runtime", realtime_output = true, runargs = {"--case", "tagged_dispatch_methods"}})
        add_tests("tagged_slot_registration_rules", {group = "runtime", realtime_output = true, runargs = {"--case", "tagged_slot_registration_rules"}})
end

if not smallfw.is_wasm() then
    target("runtime-tests-exceptions")
        set_group("tests/runtime/exceptions")
        set_kind("binary")
        set_default(false)
        if is_mode("release") then
            set_optimize("fastest")
        end
        add_options(smallfw.runtime_build_options)
        add_deps(smallfw.runtime_binary_dependency())
        add_includedirs(smallfw.project_path("Runtime", "SFRuntime", "src"))
        add_includedirs(smallfw.project_path("Runtime", "SFRuntime", "tests"))
        add_rules("smallfw.runtime.common")
        add_rules("smallfw.generic_metadata")
        add_rules("smallfw.runtime.binary")
        add_defines("SF_TEST_SUITE_LABEL=exceptions", "SF_TEST_SUITE_PROVIDER=sf_runtime_exception_cases")
        add_files("runtime-tests.m", "runtime-test-support.m", "runtime-test-exceptions.m", {mflags = {"-fno-objc-arc"}})
        if has_config("runtime-exceptions") then
            add_tests("exceptions_begin_catch_passthrough", {group = "runtime", realtime_output = true, runargs = {"--case", "exceptions_begin_catch_passthrough"}})
            add_tests("exceptions_internal_helpers", {group = "runtime", realtime_output = true, runargs = {"--case", "exceptions_internal_helpers"}})
            add_tests("exceptions_backtrace_metadata", {group = "runtime", realtime_output = true, runargs = {"--case", "exceptions_backtrace_metadata"}})
            add_tests("exceptions_backtrace_metadata_alloc_failure", {group = "runtime", realtime_output = true, runargs = {"--case", "exceptions_backtrace_metadata_alloc_failure"}})
            add_tests("exceptions_object_alloc_failure_throws", {group = "runtime", realtime_output = true, runargs = {"--case", "exceptions_object_alloc_failure_throws"}})
            add_tests("exceptions_encoding_helpers", {group = "runtime", realtime_output = true, runargs = {"--case", "exceptions_encoding_helpers"}})
            add_tests("exceptions_parse_lsda_helpers", {group = "runtime", realtime_output = true, runargs = {"--case", "exceptions_parse_lsda_helpers"}})
            add_tests("exceptions_personality_result_helper", {group = "runtime", realtime_output = true, runargs = {"--case", "exceptions_personality_result_helper"}})
            add_tests("exceptions_catch_id", {group = "runtime", realtime_output = true, runargs = {"--case", "exceptions_catch_id"}})
            add_tests("exceptions_typed_exact", {group = "runtime", realtime_output = true, runargs = {"--case", "exceptions_typed_exact"}})
            add_tests("exceptions_typed_subclass", {group = "runtime", realtime_output = true, runargs = {"--case", "exceptions_typed_subclass"}})
            add_tests("exceptions_finally_runs", {group = "runtime", realtime_output = true, runargs = {"--case", "exceptions_finally_runs"}})
            add_tests("exceptions_rethrow", {group = "runtime", realtime_output = true, runargs = {"--case", "exceptions_rethrow"}})
            add_tests("exceptions_uncaught_abort", {group = "runtime", realtime_output = true, runargs = {"--case", "exceptions_uncaught_abort"}})
            add_tests("exceptions_throw_alloc_failure_abort", {group = "runtime", realtime_output = true, runargs = {"--case", "exceptions_throw_alloc_failure_abort"}})
            add_tests("exceptions_direct_rethrow_abort", {group = "runtime", realtime_output = true, runargs = {"--case", "exceptions_direct_rethrow_abort"}})
            add_tests("exceptions_invalid_encoding_abort", {group = "runtime", realtime_output = true, runargs = {"--case", "exceptions_invalid_encoding_abort"}})
        else
            add_tests("exceptions_stubs_abort", {group = "runtime", realtime_output = true, runargs = {"--case", "exceptions_stubs_abort"}})
        end
end
